site_name: WUI

nav:
  - Домашняя: 'index.md'
  - 'Руководства':
    - Установка: 'howto/setup.md'
  - 'Справка':
    - Общие типы: 'base/common.md'
    - События: 'base/event.md'
    - Графика: 'base/graphic.md'
    - Базовые интерейсы: 'base/interfaces.md'
    - Визуальные темы: 'base/theme.md'
  - 'О библиотеке':
    - Лицензия: 'about/licence.md'
    - Контакты: 'about/contacts.md'
