site_name: WUI

nav:
  - Домашняя: 'index.md'
  - 'Руководства':
    - Получение и сборка: 'howto/receive.md'
  - 'Справка':
    - Common: 'base/common.md'
    - Event: 'base/event.md'
    - Graphic: 'base/graphic.md'
    - Interfaces: 'base/interfaces.md'
    - Theme: 'base/theme.md'
  - 'О библиотеке':
    - Лицензия: 'about/licence.md'
    - Контакты: 'about/contacts.md'
