site_name: WUI

nav:
  - Home: 'index.md'
  - 'User Guide':
    - Common: 'base/common.md'
    - Event: 'base/event.md'
    - Graphic: 'base/graphic.md'
    - Interfaces: 'base/interfaces.md'
    - Theme: 'base/theme.md'
  - 'About':
    - Licence: 'about/licence.md'
    - Contacts: 'about/contacts.md'
