site_name: WUI

nav:
  - Home: 'index.md'
  - Manuals:
    - Installation: 'howto/setup.md'
  - Help:
    - Common types: 'base/common.md'
    - Events: 'base/event.md'
    - Graphics: 'base/graphic.md'
    - Basic Interfaces: 'base/interfaces.md'
    - Visual Themes: 'base/theme.md'
  - About the Library:
    - License: 'about/licence.md'
    - Contacts: 'about/contacts.md'
